global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'manager-api'
    static_configs:
      - targets: ['manager-api:8001']
    metrics_path: /metrics

  - job_name: 'smpp-gateway'
    static_configs:
      - targets: ['smpp-gateway:2775']
    metrics_path: /metrics

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
